#!/usr/bin/env python3
"""Generate the neutral ops spec and authority fixtures (spec/ops/*.json, spec/authority/*.json) from the Round 2 IR + seed.

Usage: build_ops_spec.py [--check]   (--check regenerates in memory and diffs against disk; exit 0 iff equal)
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
R2 = ROOT.parent / "round2" / "domains"
sys.path.insert(0, str(ROOT / "scripts"))

from specgen import auth_content, mfg_ops, mfg_reads, proj_ops, proj_reads  # noqa: E402

SPEC_VERSION = "r3-ops-spec-1"
IR_FILES = {"manufacturing": R2 / "manufacturing" / "ir.json", "project": R2 / "project" / "ir.v3.json"}


def _field(p: dict) -> dict:
    f = {"name": p["name"], "type": p["type"], "required": bool(p.get("required")), "immutable": bool(p.get("immutable"))}
    for c in p.get("constraints", []) or []:
        if isinstance(c, str) and c.startswith("enum:"):
            f["enum"] = c[5:].split("|")
    return f


def resource_types(ir: dict, excluded: dict) -> list[dict]:
    out = []
    for t in ir["object_types"]:
        if t["id"] in excluded:
            continue
        fields = [_field(p) for p in t["properties"]]
        if t["id"] == "EvidenceSnapshot":
            for f in fields:
                if f["name"] == "snapshotObservedAt":
                    f["type"] = "integer"
                    f["note"] = "logical ticks (Round 2 used an ISO datetime); 1 tick = 1 second"
        for f in fields:
            if f["type"] == "datetime":  # ruling R-1: time fields hold logical-clock integer ticks, ordered numerically
                f["type"] = "logical_time"
                f.setdefault("note", "logical ticks (r3_shared.clock); numeric ordering")
        out.append({"name": t["id"], "key_field": t["primary_key"], "fields": fields})
    return out


def link_types(ir: dict, included: set) -> list[dict]:
    """Endpoints that name an IR interface are expanded to the concrete resource types implementing it."""
    impl = {i["id"]: [o["id"] for o in ir["object_types"] if i["id"] in o.get("implements", [])] for i in ir["interfaces"]}
    ends = lambda n: [n] if n not in impl else impl[n]  # noqa: E731
    out = []
    for l in ir["link_types"]:
        f, t = ends(l["from"]), ends(l["to"])
        f, t = [x for x in f if x in included], [x for x in t if x in included]
        if not f or not t:
            continue
        out.append({"name": l["id"], "from": l["from"], "to": l["to"], "from_types": f, "to_types": t,
                    "from_cardinality": l["from_cardinality"], "to_cardinality": l["to_cardinality"]})
    return out


def mfg_seed(excluded: dict) -> dict:
    raw = json.loads((R2 / "manufacturing" / "seed.json").read_text())
    objs, links = [], []
    for o in raw["ops"]:
        if o["op"] == "create" and o["type"] not in excluded:
            props = dict(o["props"])
            if o["type"] == "EvidenceSnapshot":
                props["snapshotObservedAt"] = 0
            objs.append({"type": o["type"], "key": o["key"], "props": props})
        elif o["op"] == "link" and o["src"][0] not in excluded and o["dst"][0] not in excluded:
            links.append({"link_type": o["type"], "src": f"{o['src'][0]}:{o['src'][1]}", "dst": f"{o['dst'][0]}:{o['dst'][1]}"})
    return {"objects": objs, "links": links}


def build_domain(domain: str) -> dict:
    ir = json.loads(IR_FILES[domain].read_text())
    if domain == "manufacturing":
        mod, rd, cfg, seed_fn = mfg_ops, mfg_reads, mfg_ops.CONFIG, None
        excluded, ops = rd.EXCLUDED_TYPES, mfg_ops.operations(ir["actions"])
        seed = mfg_seed(excluded)
    else:
        mod, rd, cfg = proj_ops, proj_reads, proj_ops.CONFIG
        excluded, ops, seed = rd.EXCLUDED_TYPES, proj_ops.operations(ir["actions"]), proj_reads.seed()
    reads = rd.reads(ir["functions"])
    unsupported = [dict(u) for u in rd.UNSUPPORTED]
    rtypes = resource_types(ir, excluded)
    included = {t["name"] for t in rtypes}
    covered_a = [o["name"] for o in ops] + [u["name"] for u in unsupported if u["kind"] == "action"]
    covered_f = [r["name"] for r in reads] + [u["name"] for u in unsupported if u["kind"] == "function"]
    assert sorted(covered_a) == sorted(a["id"] for a in ir["actions"]), f"{domain}: action coverage mismatch"
    assert sorted(covered_f) == sorted(f["id"] for f in ir["functions"]), f"{domain}: function coverage mismatch"
    return {
        "spec": SPEC_VERSION, "domain": domain,
        "provenance": f"generated by scripts/build_ops_spec.py from round2 {IR_FILES[domain].name} (upstream pin 8f9ff26); architecture-neutral",
        "config": cfg, "resource_types": rtypes, "link_types": link_types(ir, included),
        "operations": ops, "reads": reads, "helpers": rd.HELPERS, "unsupported": unsupported,
        "excluded_types": [{"name": k, "reason": v} for k, v in sorted(excluded.items())],
        "invariants": rd.INVARIANTS,
        "excluded_constraints": [{"ir": k, "reason": v} for k, v in sorted(rd.EXCLUDED_CONSTRAINTS.items())],
        "seed": seed,
    }


def build_auth(domain: str) -> dict:
    body = auth_content.manufacturing() if domain == "manufacturing" else auth_content.project()
    return {"spec": "r3-authority-1", "domain": domain, "semantics": auth_content.SEMANTICS,
            "provenance": "derived from round2 authority_rules/policies; 'origin' marks each grant as round2, neutral-fix or neutral-extension",
            **body}


def outputs() -> dict[Path, str]:
    out = {}
    for d in ("manufacturing", "project"):
        out[ROOT / "spec" / "ops" / f"{d}.json"] = json.dumps(build_domain(d), indent=1, sort_keys=True) + "\n"
        out[ROOT / "spec" / "authority" / f"{d}.json"] = json.dumps(build_auth(d), indent=1, sort_keys=True) + "\n"
    return out


def main(argv: list[str]) -> int:
    outs = outputs()
    if "--check" in argv:
        bad = [str(p.relative_to(ROOT)) for p, s in outs.items() if not p.exists() or p.read_text() != s]
        for b in bad:
            print(f"DIFF: {b}", file=sys.stderr)
        print("ops/authority specs up to date" if not bad else f"{len(bad)} file(s) differ")
        return 1 if bad else 0
    for p, s in outs.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(s)
        print(f"wrote {p.relative_to(ROOT)} ({len(s)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
