"""Static prose of ontology/openpona2_encoding.md (the tables are generated from src/eoo_openpona2)."""

HEAD = """# H15 v2 OpenPona encoding of the frozen EOO IR (no coreference labels)

Status: H15 v2 candidate surface (protocol/H15_V2_PREREG.json; author decision 1 in
protocol/AUTHOR_DECISIONS_2026-10-03.md). Generated by `scripts/build_openpona2_encoding.py` from
`src/eoo_openpona2/phrases.py`; do not edit by hand. Language pin: openpona-language-corpus
`97a9b9e8ca8800fda0a22f51ea59fccb6f60f35b`, parser used unmodified, no new tokens.

## 1. Model: lines carry structure and roles, the record carries ids and other atoms

A package is a text of OpenPona statements, one per line, and a record. Every line must parse RESOLVED with
`openpona.parser.parse` at the pin, with exactly the skeleton the rule assumes, and must be one of the
**{size} concrete lines** the frozen phrase table (section 6) licenses; anything else is `Invalid`/`Ambiguous`.
No line contains a number, name, punctuation or a word outside the 42 tokens (canon rule 7).

The v1 encoding (`ontology/openpona_encoding.md`) wrote every reference as an enumerated address
`<head> pi X Y` whose `pi` groups had no gloss content. Under the author's rule ("every combination of OpenPona
words must have a meaning; labels without meaning must not exist") those labels are forbidden. v2 has none:
every resource, property, parameter and reference target is written as **its kind head followed by `ni`**
(canon: `ni` bind/point, "this <head>"; canon/05 external values), and the identifier is the record atom bound
to that `ni`. Identifiers, including the id a reference points to, are record metadata (amended sidecar boundary).

## 2. Binding scheme

* **Record.** A JSON object from neutral positional keys `L<line>.a<slot>` to strings. Slots are numbered left to
  right over the `ni` tokens of the line (the order of the `ni` words in the text). The key says only where the atom
  sits; what it is and which IR field it fills is decided by the line's rule. Numeric literals are strings too; their
  kind (integer / non-integer) is stated by the line.
* **Coreference = equality of bound atoms.** `ijo ni li lon` (+ `L7.a1 = "Supplier"`) declares the object type
  Supplier; `linja ni li linja e ijo ni tan ijo ni` (+ atoms `PO_supplier`, `Supplier`, `PurchaseOrder`) refers to it
  because the atom bound to the `ijo ni` slot is the same string. The head fixes the kind, so an object type and a
  link type (or a Function and an Action) that share an id stay distinct (`ijo ni` vs `linja ni`, `ilo ni` vs `pali ni`).
* **Scoped names.** A property or parameter name is unique only inside its owner, so every statement about it names
  the owner as context: `ijo ni la sona ni li wile` ("in the context of this entity, this attribute is needed"; canon/05:
  resolution searches the narrowest explicit context). A qualified reference uses the canon possessive `pi`:
  `sona ni pi ijo ni` = "this attribute of this entity" (`<Type>.<property>`), `weka ni pi kulupu ni` = "this distant
  thing of this (imported) package" (`<import>#<name>`).
* **Prefixed references** (`auth:<id>`, `policy:<id>`) are rebuilt from the role of the slot, never stored.
* **Re-resolution.** After building the IR the compiler re-resolves every reference string with `eoo_ir.validate.Index`
  and fails (`Ambiguous`, code `denotation`, or `ir:ambiguous_ref`) if the string would denote anything other than
  what the line bound.

## 3. Several `ni` slots in one line

A line may bind up to three atoms. They are never told apart by their values: each `ni` directly follows the head
word that says what it is, and the rule fixes the role of each position. Example (row `prop.constraint`):

```
ijo ni la nasin ni li lawa e sona ni      L<n>.a1 = owner id   L<n>.a2 = constraint text   L<n>.a3 = property name
```

`a1` is the context owner (`ijo ni`, an object type id), `a2` the value of kind `nasin` (an opaque rule string),
`a3` the governed attribute (`sona ni`, resolved inside the owner). The per-row slot roles are listed in section 6.
No two `ni` are adjacent (that would be the META fold `D(ni)`); the phrase-table test checks every concrete line
parses RESOLVED with the assumed skeleton.

## 4. Blocks: bare heads mean "the one under discussion"

Three IR constructs have parts with no identifier of their own (an effect, a constructed type, a metadata value).
They are written as blocks that continue the line before them; the continuation uses the bare head (no `ni`):

* **Constructed types.** A type slot written `nasin` (bare) announces a constructed type, stated by the very next line:
  `nasin li linja e T` ({list: T}) or `nasin li T anu ala` ({optional: T}); `T` may again be `nasin` (pre-order).
  A missing or unannounced type line is `Invalid` (`missing:type_node` / `dangling_type_node`).
* **Effect fields.** `pali ni li ante e ijo ni` states one effect (order = line order); the lines directly after it,
  `ante li ma e sona ni` ("the change is scoped to this attribute") or `ante li ma e ala`, are its fields. A field
  line that follows no effect statement is `Invalid` (`dangling_statement`).
* **Metadata.** `kulupu li sona e sitelen ni` opens a package metadata member (key atom); `sitelen li sona e sitelen ni`
  / `sitelen li linja e sitelen` open a member / an item of the value currently open; a scalar line fills and completes
  it; `sitelen li pini` ("the representation is complete") completes an object or array. Unclosed or unplaceable
  statements are `Invalid` (`unclosed:metadata`, `dangling_metadata`).

## 5. Omission and order (as v1, rule R6)

A line that is absent means the IR field is absent; the compiler never writes a default. Fields with an absent/empty
distinction have an explicit empty statement (`... e ala`). Single-valued fields stated twice are `Ambiguous`;
required fields never stated are `Invalid`; statements no IR field consumes are `Invalid`; statements about an id no
line declares are `Unresolved`. Sequences (inputs, effects, properties, metadata arrays) are in line order.
"""

TAIL = """## 10. Judgment calls (recorded, not hidden)

1. **Block continuation.** A bare head (`nasin`, `ante`, `sitelen`) refers to the thing the preceding line(s) opened.
   This is position, not a label: no word distinguishes one effect/type/value from another. It is the same device as
   line order for sequences (v1 judgment call 4), extended to three anonymous constructs.
2. **Nested-type deletion.** Because a constructed type is a pre-order chain, deleting an inner constructor line of a
   nested type (e.g. the `list` line of `{list: {optional: string}}`) leaves a different, fully stated type
   (`{optional: string}`). The compiler accepts it; the line-deletion fail-closed property holds (the result is exactly
   what the mutant states), but this deletion is not detected as an error, unlike v1 where it left a dangling address.
3. **Version** uses `tenpo ni` (time-state); the canon gloss "version" belongs to the particle `anu`.
4. **Numeric types** (`kulupu ijo`, `kulupu pilin`, `tenpo sike`) keep the v1 strengths (moderate / weak / weak).
5. **Coreference by atom equality** is what the amended boundary allows (ids are metadata). The audit therefore uses
   value-consistent placeholders (equal values -> equal placeholders) in the line-only shape test.
6. **Function vs Action** is stated by the head (`ilo` vs `pali`) and by kind-specific rows; a function statement under
   an action head (or the reverse) is not a table line and is `Invalid`.

## 11. Reproduce

```bash
cd round2
.venv/bin/python scripts/build_openpona2_encoding.py --check
.venv/bin/python scripts/build_openpona2_domains.py --check
.venv/bin/python scripts/build_openpona2_ambiguity_cases.py --check
.venv/bin/python -m pytest -q -p no:cacheprovider tests/h15 -k openpona2
bash scripts/verify_h15_v2.sh
```
"""
