"""Hand-written prose of ontology/openpona_encoding.md (tables are generated from templates.py)."""

HEADER = """# H15 OpenPona encoding of the frozen EOO IR

Status: H15 Phase 2 candidate surface. Generated by `scripts/build_openpona_encoding.py` from
`src/eoo_openpona/templates.py`; do not edit by hand. Language pin: openpona-language-corpus
`97a9b9e8ca8800fda0a22f51ea59fccb6f60f35b` (contract `experiment.openpona_pin`), parser used unmodified.

## 1. Model: lines carry structure, the record carries atoms

A package is a text of OpenPona statements, one per line, and a record. Every line must parse
RESOLVED with `openpona.parser.parse` at the pin, and the parser's skeleton must equal the constituent
structure the rule assumes (`lines.expected_skeleton`); otherwise compilation fails (`Invalid`/`Ambiguous`).
No line contains a number, name, punctuation or a word outside the 42 tokens (canon rule 7).

The record is a JSON object from neutral positional keys `L<line>.a<slot>` to atom strings. Slots are
numbered left to right over the atom-binding positions the matched rule declares (in this encoding
every rule binds at most one atom, so every key is `L<n>.a1`). The key says only where the atom sits;
which IR field the atom fills is decided by the line's rule. Record values are always JSON strings,
including cardinality bounds and metadata numbers, whose kind (integer / non-integer) is stated by the line.

## 2. Addresses (canon/05_addressing.md)

Every resource, property, parameter, effect, import, external name, type node and metadata value gets a
contextual address: a kind head (section 4) followed by one or more `pi X Y` groups (X, Y two different
semantic tokens other than `tan`), e.g. `ijo pi open lon`. A rule that *declares* an address binds that
thing's identifier atom to it (e.g. `ijo pi open lon li lon` + `L7.a1 = "Supplier"`); every other line
that *mentions* the address refers to the same thing. That is how the reference graph lives in the
lines: references are address equality, never record lookups, and a reference line has no atom slot.

The `pi` groups are coreference labels with no value: the renderer enumerates them per head
(`vocab.distinguisher`), the compiler only compares whole addresses for equality, and the tests check
that any bijective renaming of addresses compiles to the identical IR. The head is not decorative: it
states what kind of thing the address is, and each reference role (section 5) accepts only certain heads.
An address declared twice is `Ambiguous`; a mentioned address never declared is `Unresolved`.

## 3. Atoms, references, omission and order

* Atom slots are written `w ni` ("this w, bound in the record"; canon/05 external values), with `w`
  naming what kind of value it is (`toki ni` text, `tenpo ni` version, `kulupu ni` a count, ...), or
  `ni` alone for metadata scalars. Identifier atoms are bound by the declaring address itself.
* Prefixed references (`auth:<id>`, `policy:<id>`) are rebuilt from the reference role, never stored
  (Gate-0 ruling 4). `<Type>.<property>` reads are a property address (its owner is known from its
  declaration). An import-qualified name `<import>#<name>` is an external address declared by
  `weka pi .. li tan <import address>` with the name as its atom. After building the IR the compiler
  re-resolves every reference string with `eoo_ir.validate.Index` and fails (`Ambiguous`, code
  `denotation`) if the string would denote anything other than what the line named.
* Omission rule (R6): a line that is absent means the IR field is absent; the compiler never writes a
  default. Fields with no schema default but an absent/empty distinction (`imports`, link `properties`,
  property `constraints`, effect `fields`, `metadata`) have an explicit empty statement (`... e ala`).
  `compensation_action: null` is `nasin weka e ala`; absent is no line. Single-valued fields stated twice
  are `Ambiguous`; required fields never stated are `Invalid`; statements no IR field consumes are `Invalid`.
* Order: function/action `inputs`, action `effects` and metadata arrays are sequences; their order is the
  order of their declaring lines. Set-valued lists are also emitted and read in line order (so the round
  trip is exact, not only equivalent); a duplicated element is a second, identical line.
"""

FOOTER = """## 9. Judgment calls (canon unclear; recorded, not hidden)

1. **Addresses as coreference.** Canon/05 persists `bound_ref` in the record; H15 forbids putting the
   reference graph there, so references are carried by repeating the address in the line. The `pi`
   groups are enumerated labels with no gloss content (like bound-variable names). If a reviewer rules
   that such labels are an "arbitrary token assignment" under R4, every reference slot in the IR is
   affected (the whole reference graph), and H15 would be hit by the sidecar or cipher falsifier.
2. **Version** uses `tenpo ni` (time-state); the canon gloss "version" belongs to the particle `anu`,
   which can never carry content.
3. **Numeric types.** No token has a numeric gloss (`mute`/`nanpa` are outside the 42; canon/01 concedes
   weakness at scalar magnitude). integer = `kulupu ijo` (aggregate of discrete entities: a count) is
   moderate; number = `kulupu pilin` (aggregate of an evaluated magnitude) and date = `tenpo sike` are
   weak. These are listed in section 8, not in the gaps file.
4. **Line order** carries sequence order for `inputs`, `effects` and metadata arrays (no gloss is
   involved; this is how every text surface writes a list, including the direct DSL baseline).
5. **Duplicates** in set-valued lists are repeated identical lines (one line per element). For
   reference lists (e.g. `implements: [I, I]`) the two lines are the same statement twice.
6. **Function vs Action** is stated twice in the line: by the head (`ilo` vs `pali`) and by their
   rules (`ilo .. li ante ala e ijo` purity vs. action-only rules); a function line under an action head
   (or the reverse) matches no rule and is `Invalid`.

## 10. Reproduce

```bash
cd round2
.venv/bin/python scripts/build_openpona_encoding.py --check
.venv/bin/python scripts/build_openpona_domains.py --check
.venv/bin/python -m pytest -q -p no:cacheprovider tests/h15 -k openpona
```
"""
