"""Generate models_gen.py (typed per-operation request models) from the neutral ops specs.

    python -m conventional.codegen          # (re)write models_gen.py
    python -m conventional.codegen --check  # exit 1 if the committed file differs from regeneration
"""
from __future__ import annotations

import sys
from pathlib import Path

from r3_shared.opsspec import DOMAINS, ROUND3, load_ops_spec

OUT = Path(__file__).with_name("models_gen.py")
HEADER = '''"""GENERATED by conventional/codegen.py from spec/ops/*.json - do not edit; regenerate with
`python -m conventional.codegen`. One frozen request model per operation."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar

from .validation import validate_inputs
'''


def _cls(op_name: str) -> str:
    return "".join(p.capitalize() for p in op_name.split("_")) + "Request"


def render(root: Path = ROUND3) -> str:
    out = [HEADER]
    reg = []
    for domain in DOMAINS:
        for op in load_ops_spec(domain, root)["operations"]:
            c = _cls(op["name"])
            schema = tuple((i["name"], i["type"], bool(i["required"])) for i in op["inputs"])
            res = {i["name"]: i["resource_type"] for i in op["inputs"] if i["type"] == "resource"}
            appr = op["approval"]
            out.append(f'''

@dataclass(frozen=True, kw_only=True)
class {c}:
    OPERATION: ClassVar[str] = {op["name"]!r}
    DOMAIN: ClassVar[str] = {domain!r}
    SCHEMA: ClassVar[tuple] = {schema!r}
    RESOURCES: ClassVar[dict] = {res!r}
    GATED: ClassVar[tuple] = {tuple(op["gated_inputs"])!r}
    APPROVAL: ClassVar[Any] = {(appr or {}).get("approver_operation")!r}
''' + "".join(
                f"    {n}: {'Any' if k in ('json',) else ('int' if k == 'integer' else 'str')}"
                f"{'' if r else ' | None = None'}\n" for n, k, r in sorted(schema, key=lambda s: not s[2])) + f'''
    @classmethod
    def from_args(cls, args: dict) -> "{c}":
        return cls(**validate_inputs(cls.SCHEMA, args))

    def inputs(self) -> dict:
        return {{n: getattr(self, n) for n, _, _ in self.SCHEMA if getattr(self, n) is not None}}
''')
            reg.append((op["name"], c))
    out.append("\n\nOPERATION_MODELS: dict[str, type] = {\n" + "".join(f"    {n!r}: {c},\n" for n, c in reg) + "}\n")
    return "".join(out)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("models_gen.py is stale: run `python -m conventional.codegen`")
            return 1
        print("models_gen.py up to date")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
