"""GENERATED by conventional/codegen.py from spec/ops/*.json - do not edit; regenerate with
`python -m conventional.codegen`. One frozen request model per operation."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar

from .validation import validate_inputs


@dataclass(frozen=True, kw_only=True)
class TransferInventoryRequest:
    OPERATION: ClassVar[str] = 'transfer_inventory'
    DOMAIN: ClassVar[str] = 'manufacturing'
    SCHEMA: ClassVar[tuple] = (('source_warehouse', 'resource', True), ('destination_warehouse', 'resource', True), ('part', 'resource', True), ('quantity', 'integer', True), ('work_order', 'resource', False))
    RESOURCES: ClassVar[dict] = {'source_warehouse': 'Warehouse', 'destination_warehouse': 'Warehouse', 'part': 'Part', 'work_order': 'WorkOrder'}
    GATED: ClassVar[tuple] = ('source_warehouse', 'destination_warehouse', 'part', 'quantity', 'work_order')
    APPROVAL: ClassVar[Any] = 'approval:large_transfer'
    source_warehouse: str
    destination_warehouse: str
    part: str
    quantity: int
    work_order: str | None = None

    @classmethod
    def from_args(cls, args: dict) -> "TransferInventoryRequest":
        return cls(**validate_inputs(cls.SCHEMA, args))

    def inputs(self) -> dict:
        return {n: getattr(self, n) for n, _, _ in self.SCHEMA if getattr(self, n) is not None}


@dataclass(frozen=True, kw_only=True)
class ExpeditePurchaseOrderRequest:
    OPERATION: ClassVar[str] = 'expedite_purchase_order'
    DOMAIN: ClassVar[str] = 'manufacturing'
    SCHEMA: ClassVar[tuple] = (('po_id', 'resource', True), ('expedite_fee', 'integer', True))
    RESOURCES: ClassVar[dict] = {'po_id': 'PurchaseOrder'}
    GATED: ClassVar[tuple] = ('po_id', 'expedite_fee')
    APPROVAL: ClassVar[Any] = 'approval:expedite'
    po_id: str
    expedite_fee: int

    @classmethod
    def from_args(cls, args: dict) -> "ExpeditePurchaseOrderRequest":
        return cls(**validate_inputs(cls.SCHEMA, args))

    def inputs(self) -> dict:
        return {n: getattr(self, n) for n, _, _ in self.SCHEMA if getattr(self, n) is not None}


@dataclass(frozen=True, kw_only=True)
class RescheduleWorkOrderRequest:
    OPERATION: ClassVar[str] = 'reschedule_work_order'
    DOMAIN: ClassVar[str] = 'manufacturing'
    SCHEMA: ClassVar[tuple] = (('work_order_id', 'resource', True), ('new_planned_start', 'integer', True))
    RESOURCES: ClassVar[dict] = {'work_order_id': 'WorkOrder'}
    GATED: ClassVar[tuple] = ('work_order_id', 'new_planned_start')
    APPROVAL: ClassVar[Any] = 'approval:reschedule'
    work_order_id: str
    new_planned_start: int

    @classmethod
    def from_args(cls, args: dict) -> "RescheduleWorkOrderRequest":
        return cls(**validate_inputs(cls.SCHEMA, args))

    def inputs(self) -> dict:
        return {n: getattr(self, n) for n, _, _ in self.SCHEMA if getattr(self, n) is not None}


@dataclass(frozen=True, kw_only=True)
class CreateHypothesisRequest:
    OPERATION: ClassVar[str] = 'create_hypothesis'
    DOMAIN: ClassVar[str] = 'project'
    SCHEMA: ClassVar[tuple] = (('claim', 'string', True),)
    RESOURCES: ClassVar[dict] = {}
    GATED: ClassVar[tuple] = ('claim',)
    APPROVAL: ClassVar[Any] = None
    claim: str

    @classmethod
    def from_args(cls, args: dict) -> "CreateHypothesisRequest":
        return cls(**validate_inputs(cls.SCHEMA, args))

    def inputs(self) -> dict:
        return {n: getattr(self, n) for n, _, _ in self.SCHEMA if getattr(self, n) is not None}


@dataclass(frozen=True, kw_only=True)
class EditThresholdRequest:
    OPERATION: ClassVar[str] = 'edit_threshold'
    DOMAIN: ClassVar[str] = 'project'
    SCHEMA: ClassVar[tuple] = (('threshold', 'resource', True), ('value', 'json', True))
    RESOURCES: ClassVar[dict] = {'threshold': 'Threshold'}
    GATED: ClassVar[tuple] = ('threshold', 'value')
    APPROVAL: ClassVar[Any] = None
    threshold: str
    value: Any

    @classmethod
    def from_args(cls, args: dict) -> "EditThresholdRequest":
        return cls(**validate_inputs(cls.SCHEMA, args))

    def inputs(self) -> dict:
        return {n: getattr(self, n) for n, _, _ in self.SCHEMA if getattr(self, n) is not None}


@dataclass(frozen=True, kw_only=True)
class PreregisterHypothesisRequest:
    OPERATION: ClassVar[str] = 'preregister_hypothesis'
    DOMAIN: ClassVar[str] = 'project'
    SCHEMA: ClassVar[tuple] = (('hypothesis', 'resource', True), ('freeze_hash', 'string', True))
    RESOURCES: ClassVar[dict] = {'hypothesis': 'Hypothesis'}
    GATED: ClassVar[tuple] = ('hypothesis', 'freeze_hash')
    APPROVAL: ClassVar[Any] = None
    hypothesis: str
    freeze_hash: str

    @classmethod
    def from_args(cls, args: dict) -> "PreregisterHypothesisRequest":
        return cls(**validate_inputs(cls.SCHEMA, args))

    def inputs(self) -> dict:
        return {n: getattr(self, n) for n, _, _ in self.SCHEMA if getattr(self, n) is not None}


@dataclass(frozen=True, kw_only=True)
class NewExperimentVersionRequest:
    OPERATION: ClassVar[str] = 'new_experiment_version'
    DOMAIN: ClassVar[str] = 'project'
    SCHEMA: ClassVar[tuple] = (('experiment', 'resource', True), ('contract_version', 'resource', True))
    RESOURCES: ClassVar[dict] = {'experiment': 'Experiment', 'contract_version': 'ContractVersion'}
    GATED: ClassVar[tuple] = ('experiment', 'contract_version')
    APPROVAL: ClassVar[Any] = None
    experiment: str
    contract_version: str

    @classmethod
    def from_args(cls, args: dict) -> "NewExperimentVersionRequest":
        return cls(**validate_inputs(cls.SCHEMA, args))

    def inputs(self) -> dict:
        return {n: getattr(self, n) for n, _, _ in self.SCHEMA if getattr(self, n) is not None}


@dataclass(frozen=True, kw_only=True)
class StartRunRequest:
    OPERATION: ClassVar[str] = 'start_run'
    DOMAIN: ClassVar[str] = 'project'
    SCHEMA: ClassVar[tuple] = (('hypothesis', 'resource', True),)
    RESOURCES: ClassVar[dict] = {'hypothesis': 'Hypothesis'}
    GATED: ClassVar[tuple] = ('hypothesis',)
    APPROVAL: ClassVar[Any] = None
    hypothesis: str

    @classmethod
    def from_args(cls, args: dict) -> "StartRunRequest":
        return cls(**validate_inputs(cls.SCHEMA, args))

    def inputs(self) -> dict:
        return {n: getattr(self, n) for n, _, _ in self.SCHEMA if getattr(self, n) is not None}


@dataclass(frozen=True, kw_only=True)
class AttachEvidenceRequest:
    OPERATION: ClassVar[str] = 'attach_evidence'
    DOMAIN: ClassVar[str] = 'project'
    SCHEMA: ClassVar[tuple] = (('hypothesis', 'resource', True), ('evidence', 'resource', True))
    RESOURCES: ClassVar[dict] = {'hypothesis': 'Hypothesis', 'evidence': 'Evidence'}
    GATED: ClassVar[tuple] = ('hypothesis', 'evidence')
    APPROVAL: ClassVar[Any] = None
    hypothesis: str
    evidence: str

    @classmethod
    def from_args(cls, args: dict) -> "AttachEvidenceRequest":
        return cls(**validate_inputs(cls.SCHEMA, args))

    def inputs(self) -> dict:
        return {n: getattr(self, n) for n, _, _ in self.SCHEMA if getattr(self, n) is not None}


@dataclass(frozen=True, kw_only=True)
class EvaluateHypothesisRequest:
    OPERATION: ClassVar[str] = 'evaluate_hypothesis'
    DOMAIN: ClassVar[str] = 'project'
    SCHEMA: ClassVar[tuple] = (('hypothesis', 'resource', True),)
    RESOURCES: ClassVar[dict] = {'hypothesis': 'Hypothesis'}
    GATED: ClassVar[tuple] = ('hypothesis',)
    APPROVAL: ClassVar[Any] = None
    hypothesis: str

    @classmethod
    def from_args(cls, args: dict) -> "EvaluateHypothesisRequest":
        return cls(**validate_inputs(cls.SCHEMA, args))

    def inputs(self) -> dict:
        return {n: getattr(self, n) for n, _, _ in self.SCHEMA if getattr(self, n) is not None}


@dataclass(frozen=True, kw_only=True)
class SupersedeHypothesisRequest:
    OPERATION: ClassVar[str] = 'supersede_hypothesis'
    DOMAIN: ClassVar[str] = 'project'
    SCHEMA: ClassVar[tuple] = (('hypothesis', 'resource', True), ('successor', 'resource', True))
    RESOURCES: ClassVar[dict] = {'hypothesis': 'Hypothesis', 'successor': 'Hypothesis'}
    GATED: ClassVar[tuple] = ('hypothesis', 'successor')
    APPROVAL: ClassVar[Any] = None
    hypothesis: str
    successor: str

    @classmethod
    def from_args(cls, args: dict) -> "SupersedeHypothesisRequest":
        return cls(**validate_inputs(cls.SCHEMA, args))

    def inputs(self) -> dict:
        return {n: getattr(self, n) for n, _, _ in self.SCHEMA if getattr(self, n) is not None}


@dataclass(frozen=True, kw_only=True)
class RecordDecisionRequest:
    OPERATION: ClassVar[str] = 'record_decision'
    DOMAIN: ClassVar[str] = 'project'
    SCHEMA: ClassVar[tuple] = (('decision', 'resource', True), ('contract_version', 'resource', True))
    RESOURCES: ClassVar[dict] = {'decision': 'Decision', 'contract_version': 'ContractVersion'}
    GATED: ClassVar[tuple] = ('decision', 'contract_version')
    APPROVAL: ClassVar[Any] = None
    decision: str
    contract_version: str

    @classmethod
    def from_args(cls, args: dict) -> "RecordDecisionRequest":
        return cls(**validate_inputs(cls.SCHEMA, args))

    def inputs(self) -> dict:
        return {n: getattr(self, n) for n, _, _ in self.SCHEMA if getattr(self, n) is not None}


@dataclass(frozen=True, kw_only=True)
class FlagOrphanComponentRequest:
    OPERATION: ClassVar[str] = 'flag_orphan_component'
    DOMAIN: ClassVar[str] = 'project'
    SCHEMA: ClassVar[tuple] = (('component', 'resource', True),)
    RESOURCES: ClassVar[dict] = {'component': 'Component'}
    GATED: ClassVar[tuple] = ('component',)
    APPROVAL: ClassVar[Any] = None
    component: str

    @classmethod
    def from_args(cls, args: dict) -> "FlagOrphanComponentRequest":
        return cls(**validate_inputs(cls.SCHEMA, args))

    def inputs(self) -> dict:
        return {n: getattr(self, n) for n, _, _ in self.SCHEMA if getattr(self, n) is not None}


OPERATION_MODELS: dict[str, type] = {
    'transfer_inventory': TransferInventoryRequest,
    'expedite_purchase_order': ExpeditePurchaseOrderRequest,
    'reschedule_work_order': RescheduleWorkOrderRequest,
    'create_hypothesis': CreateHypothesisRequest,
    'edit_threshold': EditThresholdRequest,
    'preregister_hypothesis': PreregisterHypothesisRequest,
    'new_experiment_version': NewExperimentVersionRequest,
    'start_run': StartRunRequest,
    'attach_evidence': AttachEvidenceRequest,
    'evaluate_hypothesis': EvaluateHypothesisRequest,
    'supersede_hypothesis': SupersedeHypothesisRequest,
    'record_decision': RecordDecisionRequest,
    'flag_orphan_component': FlagOrphanComponentRequest,
}
