"""Generated principal / object-set cases (Hypothesis) for the security differential."""
from __future__ import annotations

import hashlib
import json

from hypothesis import HealthCheck, Phase, given, seed, settings
from hypothesis import strategies as st

DECOY_ROLES = ["admin", "none", "agent", "guest"]
DECOY_RELS = ["owner", "viewer", "stranger"]


def vocab(ir: dict) -> tuple:
    """(roles, relations, {relation: object type it is held on}) taken from the rule selectors, plus decoys."""
    roles, rels, rel_type = [], [], {}
    types = {o["id"].lower(): o["id"] for o in ir["object_types"]}
    for r in ir["authority_rules"]:
        s = r["principal_selector"]
        if s.startswith("role:"):
            roles.append(s[5:])
        elif "#" in s:
            t, rel = s.split("#", 1)
            rels.append(rel)
            if t.lower() in types:
                rel_type[rel] = types[t.lower()]
    return sorted(set(roles) | set(DECOY_ROLES)), sorted(set(rels) | set(DECOY_RELS)), rel_type


def build_case(ir: dict, rnd, fixed_world: dict | None = None) -> dict:
    """One case drawn with ``rnd`` (a Hypothesis-seeded random.Random), probabilities tuned so every capability path is hit."""
    roles_v, rels_v, rel_type = vocab(ir)
    types = [o["id"] for o in ir["object_types"]]
    if fixed_world is not None:
        objs = {t: list(v) for t, v in fixed_world.items()}
    else:
        objs = {t: [f"{t}-{i}" for i in sorted(rnd.sample(range(3), rnd.choice([0, 1, 1, 2, 2])))] for t in types}
        for t in set(rel_type.values()):  # keep the object types the relation selectors range over mostly populated
            if not objs[t] and rnd.random() < 0.85:
                objs[t] = [f"{t}-{i}" for i in sorted(rnd.sample(range(3), rnd.choice([1, 2])))]
    pre = sorted(rnd.sample(objs["Threshold"], rnd.randint(0, min(2, len(objs["Threshold"]))))) if objs.get("Threshold") else []
    world = {"objects": objs, "flags": {"preregistered": pre, "fault": rnd.random() < 0.03}}

    def principal(depth: int) -> dict:
        roles = [r for r in roles_v if rnd.random() < (0.5 if r not in DECOY_ROLES else 0.2)]
        rels = []
        for rel in rels_v:
            if rnd.random() < 0.45:
                t = rel_type.get(rel) or rnd.choice(types)
                held = [k for k in objs.get(t, []) if rnd.random() < 0.75]
                rels += [[t, k, rel] for k in held]
                if rnd.random() < 0.15:
                    rels.append([t, "ghost", rel])
        if rnd.random() < 0.15:
            rels.append([rnd.choice(types), rnd.choice(["ghost", "x"]), rnd.choice(rels_v)])
        p = {"pid": f"p{depth}-{rnd.randint(0, 3)}", "roles": sorted(roles), "relations": sorted(map(list, {tuple(r) for r in rels})),
             "delegated_by": None}
        if depth < 3 and rnd.random() < 0.4:
            p["delegated_by"] = principal(depth + 1)
        return p
    return {"principal": principal(0), "registered": rnd.random() < 0.95, "world": world}


def case_strategy(ir: dict, fixed_world: dict | None = None):
    return st.randoms(use_true_random=True).map(lambda rnd: build_case(ir, rnd, fixed_world))


def case_sha(c: dict) -> str:
    return hashlib.sha256(json.dumps(c, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def unique_cases(ir: dict, n: int, base_seed: int, fixed_world: dict | None = None) -> list:
    """>= n distinct cases (by canonical hash), generated by Hypothesis under derived seeds."""
    seen, out, rnd = set(), [], 0
    strat = case_strategy(ir, fixed_world)
    while len(out) < n and rnd < 50:
        want = n - len(out)

        @seed(base_seed * 1000 + rnd)
        @settings(max_examples=int(want * 1.15) + 50, deadline=None, database=None, phases=[Phase.generate],
                  suppress_health_check=list(HealthCheck))
        @given(strat)
        def collect(c):
            h = case_sha(c)
            if h not in seen and len(out) < n:
                seen.add(h)
                out.append(c)
        collect()
        rnd += 1
    return out
