"""Emit the query surface, function tools, action tools and the per-principal AgentSurface class for one package."""
from __future__ import annotations

from .gen_sdk import call_base, implementers, link_card
from .naming import ident

HEADER = '''"""GENERATED by eoo_toolchain: query / function / action tools and AgentSurface for package {pid}. Do not edit."""
from __future__ import annotations

from paladin.toolchain.runtime import AgentSurfaceBase, follow_links, get_object, interface_list, list_objects

from . import sdk
from .caps import TABLES
'''


def interface_tool_src(iface: str, impls: list) -> str:
    """Generic: names the interface only, never an implementer (the H21 hard-coding mutant patches this)."""
    return f"    return interface_list(client, {iface!r}, sdk.CLASSES)"


def follow_tool_src(lk: dict) -> list:
    (_fmin, fmax), (_tmin, tmax) = link_card(lk)
    return [f"def follow_{ident(lk['id'])}(client, type, key, direction='out'):",
            f"    single = {fmax == 1!r} if direction == 'out' else {tmax == 1!r}",
            f"    return follow_links(client, {lk['id']!r}, sdk.CLASSES[type], key, direction, sdk.CLASSES, single)", "", ""]


def generate(ir: dict) -> tuple:
    """(module text, tool inventory {name: {kind, ref, capability}})"""
    inv: dict = {}
    L = HEADER.format(pid=ir["package_id"]).splitlines() + ["", ""]
    q, fnt, act = [], [], []
    for o in ir["object_types"]:
        t = ident(o["id"])
        L += [f"def get_{t}(client, key):", f"    return get_object(client, sdk.{t}, key)", "", "",
              f"def list_{t}(client):", f"    return list_objects(client, sdk.{t})", "", ""]
        q += [(f"get_{t}", f"get:{o['id']}", f"get_{t}"), (f"list_{t}", f"list:{o['id']}", f"list_{t}")]
    for i in ir["interfaces"]:
        t = ident(i["id"])
        L += [f"def query_{t}(client):", interface_tool_src(i["id"], implementers(ir, i["id"])), "", ""]
        q.append((f"query_{t}", f"query:{i['id']}", f"query_{t}"))
    for lk in ir["link_types"]:
        L += follow_tool_src(lk)
        q.append((f"follow_{ident(lk['id'])}", f"follow:{lk['id']}", f"follow_{ident(lk['id'])}"))
    for f in ir["functions"]:
        t = ident(f["id"])
        L += [f"def call_{t}(client, pid, **args):", f"    return sdk.Fn_{t}(**args).call(client, pid)", "", ""]
        fnt.append((f"call_{t}", f"call:{f['id']}", f"call_{t}"))
    for a in ir["actions"]:
        t = ident(a["id"])
        L += [f"def act_{t}(client, pid, idempotency_key=None, **inputs):",
              f"    return sdk.Act_{t}(**inputs).propose(client, pid, idempotency_key)", "", ""]
        act.append((f"act_{t}", a["id"], f"act_{t}"))
    L += ["class AgentSurface(AgentSurfaceBase):", "    TABLES = TABLES"]
    L.append("    QUERY_TOOLS = {" + ", ".join(f"{n!r}: ({c!r}, {fn})" for n, c, fn in q) + "}")
    L.append("    FUNCTION_TOOLS = {" + ", ".join(f"{n!r}: ({c!r}, {fn})" for n, c, fn in fnt) + "}")
    L.append("    ACTION_TOOLS = {" + ", ".join(f"{n!r}: ({c!r}, {fn})" for n, c, fn in act) + "}")
    names = [n for n, _c, _f in q + fnt + act]
    if len(set(names)) != len(names):
        raise ValueError("tool name collision after identifier mapping")
    for n, c, _f in q:
        inv[n] = {"kind": "query", "capability": c}
    for n, c, _f in fnt:
        inv[n] = {"kind": "function", "capability": c}
    for n, c, _f in act:
        inv[n] = {"kind": "action", "capability": "action:" + c}
    return "\n".join(L) + "\n", inv
