"""Emit the typed SDK module: object dataclasses, interface protocols, cardinality-aware link accessors, and distinct
Function-call / Action-request types. Pure text generation from the IR; hooks (fields_of, link_card, call_base) are the
points the H21 mutation proof patches."""
from __future__ import annotations

from .naming import exact_ident, is_optional, prop_annotation, py_type, ref_target

HEADER = '''"""GENERATED by eoo_toolchain from package {pid} {ver} (ir sha256 {sha}). Do not edit; regenerate."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Literal, Optional, Protocol

from paladin.toolchain.runtime import ActionRequest, FunctionCall, Key, Obj, follow_links

PACKAGE_ID = {pid!r}
PACKAGE_VERSION = {ver!r}
'''


def fields_of(obj: dict) -> list:
    """Properties that become dataclass fields (required first: dataclass default ordering)."""
    props = list(obj["properties"])
    return [p for p in props if p.get("required")] + [p for p in props if not p.get("required")]


def link_card(link: dict) -> tuple:
    f, t = link["from_cardinality"], link["to_cardinality"]
    return (f["min"], f["max"]), (t["min"], t["max"])


def call_base(kind: str) -> str:
    return "FunctionCall" if kind == "function" else "ActionRequest"


def implementers(ir: dict, end: str) -> list:
    if any(o["id"] == end for o in ir["object_types"]):
        return [end]
    return sorted(o["id"] for o in ir["object_types"] if end in o.get("implements", []))


def accessors(ir: dict, type_id: str) -> list:
    """Link accessors for one object type: out_<L> where it can be the from end, in_<L> where it can be the to end."""
    out = []
    for lk in ir["link_types"]:
        (fmin, fmax), (tmin, tmax) = link_card(lk)
        if type_id in implementers(ir, lk["from"]):
            single = fmax == 1
            ann = f"Optional[{lk['to']}]" if single else f"list[{lk['to']}]"
            out.append((f"out_{lk['id']}", lk["id"], "out", single, ann))
        if type_id in implementers(ir, lk["to"]):
            single = tmax == 1
            ann = f"Optional[{lk['from']}]" if single else f"list[{lk['from']}]"
            out.append((f"in_{lk['id']}", lk["id"], "in", single, ann))
    return out


def object_class(ir: dict, o: dict) -> list:
    lines = ["@dataclass(frozen=True)", f"class {exact_ident(o['id'])}(Obj):",
             f"    TYPE: ClassVar[str] = {o['id']!r}", f"    PK: ClassVar[str] = {o['primary_key']!r}",
             f"    IMPLEMENTS: ClassVar[tuple] = {tuple(o.get('implements', []))!r}"]
    for p in fields_of(o):
        default = "" if p.get("required") else " = None"
        lines.append(f"    {exact_ident(p['name'])}: {prop_annotation(p)}{default}")
    lines += [f"    def key(self) -> Key:", f"        return self.{o['primary_key']}"]
    for name, link, direction, single, ann in accessors(ir, o["id"]):
        lines += [f"    def {name}(self, client) -> {ann}:",
                  f"        return follow_links(client, {link!r}, type(self), self.key(), {direction!r}, CLASSES, {single!r})"]
    return lines + ["", ""]


def interface_class(i: dict) -> list:
    lines = [f"class {exact_ident(i['id'])}(Protocol):", f"    IFACE: ClassVar[str] = {i['id']!r}"]
    lines += [f"    {exact_ident(p['name'])}: {prop_annotation(p)}" for p in i["required_properties"]]
    return lines + ["", ""]


def call_class(kind: str, r: dict) -> list:
    prefix = "Fn_" if kind == "function" else "Act_"
    lines = ["@dataclass(frozen=True)", f"class {prefix}{exact_ident(r['id'])}({call_base(kind)}):", f"    ID: ClassVar[str] = {r['id']!r}"]
    if kind == "function":
        lines.append(f"    OUTPUT: ClassVar[str] = {py_type(r['output'])!r}")
    else:
        lines += [f"    CAPABILITY: ClassVar[str] = {'action:' + r['id']!r}", f"    IDEMPOTENCY: ClassVar[str] = {r['idempotency']!r}"]
    ins = sorted(r["inputs"], key=lambda p: not p.get("required", True))
    for p in ins:
        req = p.get("required", True)
        ann = py_type(p["type"]) if req or is_optional(p["type"]) else f"Optional[{py_type(p['type'])}]"
        lines.append(f"    {exact_ident(p['name'])}: {ann}" + ("" if req else " = None"))
    if not ins:
        lines.append("    pass")
    return lines + ["", ""]


def metadata(ir: dict) -> dict:
    return {
        "object_types": {o["id"]: {"pk": o["primary_key"], "properties": [p["name"] for p in fields_of(o)],
                                   "implements": list(o.get("implements", [])),
                                   "links": [a[0] for a in accessors(ir, o["id"])]} for o in ir["object_types"]},
        "interfaces": {i["id"]: {"required_properties": [p["name"] for p in i["required_properties"]],
                                 "implementers": implementers(ir, i["id"])} for i in ir["interfaces"]},
        "links": {lk["id"]: {"from": lk["from"], "to": lk["to"], "from_cardinality": list(link_card(lk)[0]),
                             "to_cardinality": list(link_card(lk)[1])} for lk in ir["link_types"]},
        "functions": {f["id"]: {"class": "Fn_" + f["id"], "inputs": [p["name"] for p in f["inputs"]], "output": f["output"]} for f in ir["functions"]},
        "actions": {a["id"]: {"class": "Act_" + a["id"], "inputs": [p["name"] for p in a["inputs"]]} for a in ir["actions"]},
    }


def generate(ir: dict, sha: str) -> str:
    names = [o["id"] for o in ir["object_types"]] + [i["id"] for i in ir["interfaces"]]
    if len(set(names)) != len(names):
        raise ValueError("an object type and an interface share an id; the SDK namespace would collide")
    lines = HEADER.format(pid=ir["package_id"], ver=ir["version"], sha=sha).splitlines() + ["", ""]
    for i in ir["interfaces"]:
        lines += interface_class(i)
    for o in ir["object_types"]:
        lines += object_class(ir, o)
    lines.append("CLASSES: dict = {" + ", ".join(f"{o['id']!r}: {o['id']}" for o in ir["object_types"]) + "}")
    lines += ["", ""]
    for f in ir["functions"]:
        lines += call_class("function", f)
    for a in ir["actions"]:
        lines += call_class("action", a)
    lines.append("MANIFEST: dict = " + repr(metadata(ir)))
    return "\n".join(lines) + "\n"
