"""Emit the compiled capability tables of a generated surface (authority rules, per-action refs, ref inputs, type
conformance). The decision procedure is the generic eoo_toolchain.capdecide; only data is generated per domain."""
from __future__ import annotations

from .naming import ref_target
from .selectors import compile_rule, type_lookup


def rule_table(ir: dict) -> dict:
    look = type_lookup(ir)
    return {r["id"]: compile_rule(r, look) for r in ir["authority_rules"]}


def action_refs(ir: dict, a: dict, rules: dict) -> list:
    """Authority refs of an action: the local rule id, or an ``import:`` mark (a ref the Toolchain cannot resolve)."""
    out = []
    for ref in a["authority_refs"]:
        rid = ref[len("auth:"):] if ref.startswith("auth:") else None
        out.append(rid if rid in rules else "import:" + ref)
    return out


def ref_slots(a: dict) -> list:
    slots = []
    for p in a["inputs"]:
        tgt = ref_target(p["type"])
        if tgt:
            optional = (not p.get("required", True)) or (isinstance(p["type"], dict) and "optional" in p["type"])
            slots.append({"name": p["name"], "declared": tgt[0], "required": not optional, "list": tgt[1]})
    return slots


def action_table(ir: dict, rules: dict) -> dict:
    out = {}
    for a in ir["actions"]:
        auth = action_refs(ir, a, rules)
        caps = sorted({rules[r]["capability"] for r in auth if r in rules and rules[r]["effect"] == "allow"
                       and rules[r]["capability"].startswith("approval:")})
        out[a["id"]] = {"authority": auth, "slots": ref_slots(a), "approval_caps": caps,
                        "effect_targets": [e["target"] for e in a["effects"]]}
    return out


def tables(ir: dict) -> dict:
    rules = rule_table(ir)
    impl = {i["id"]: sorted(o["id"] for o in ir["object_types"] if i["id"] in o.get("implements", [])) for i in ir["interfaces"]}
    return {"rules": rules, "actions": action_table(ir, rules), "implementers": impl}


def generate(ir: dict) -> str:
    return ('"""GENERATED by eoo_toolchain: compiled authority tables for package %s. Do not edit."""\n\nTABLES: dict = %r\n'
            % (ir["package_id"], tables(ir)))
