"""W5 — forensic query, "given an outcome six simulated months later"
(spec 10; spec 14 R10: "six months later cannot literally wait six
months" — this workload treats an ALREADY-COMPLETED decision as if it
were being investigated long after the fact, the same stance Phase 7's
own historical-corpus replay tests take).

Runs the SAME seven-question forensic reconstruction
(docs/experiment/spec/11_acceptance_criteria.md B.10: who / what evidence
/ what policy / what authorization / what action / what actual outcome /
what changed next) against a real OBSERVED_SUCCESS decision from EACH
variant, counting: manual log sources needed, number of distinct calls,
and completeness (can all seven be answered at all).
"""

from __future__ import annotations

import time

from tests.ab import synthetic
from tests.ab.harness import Harness


def _forensic_ontology(h: Harness, decision_id: str) -> dict:
    calls = 0
    t0 = time.monotonic()
    decision = h.ontology.get(decision_id).json()
    calls += 1
    answers = {
        "who": decision.get("actor_id"),
        "what_evidence": bool((decision.get("evidence_snapshot") or {}).get("facts_used")),
        "what_policy": (decision.get("policy_result") or {}).get("outcome"),
        "what_authorization": (decision.get("authorization_result") or {}).get("outcome"),
        "what_action": f"{decision.get('action_type')} v{decision.get('action_version')} {decision.get('parameters')}",
    }
    # what actual outcome / what changed next — needs the linked execution/outcome.
    execution_id = f"AX-{decision_id}"
    execution = h.ontology.client.get(f"/executions/{execution_id}")
    calls += 1
    outcome_body = None
    if execution.status_code == 200:
        outcome_id = execution.json().get("outcomeId") or execution.json().get("outcome_id")
        if outcome_id:
            outcome_resp = h.ontology.client.get(f"/outcomes/{outcome_id}")
            calls += 1
            if outcome_resp.status_code == 200:
                outcome_body = outcome_resp.json()
    answers["what_actual_outcome"] = (outcome_body or {}).get("reconciliationState") or (outcome_body or {}).get("reconciliation_state")
    answers["what_changed_next"] = "no subsequent decision generated by this workload (see module docstring — a real forensic query would search decisions concerning the same entities)"
    elapsed = time.monotonic() - t0
    return {"variant": "ontology", "answers": answers, "calls": calls, "manual_sources": 1, "elapsed_s": elapsed, "complete": all(v not in (None, False, "") for k, v in answers.items() if k != "what_changed_next")}


def _forensic_baseline(h: Harness, decision_id: str) -> dict:
    calls = 0
    t0 = time.monotonic()
    decision = h.baseline.get(decision_id).json()
    calls += 1  # the ONE call already carries gate_results nested (services/baseline/store.py::get_decision) — no second round trip needed for who/evidence/policy/authorization
    answers = {
        "who": decision.get("actor_id"),
        "what_evidence": bool((decision.get("evidence_snapshot") or {}).get("facts_used")),
        "what_policy": (decision.get("policy_result") or {}).get("outcome"),
        "what_authorization": (decision.get("authorization_result") or {}).get("outcome"),
        "what_action": f"{decision.get('action_type')} v{decision.get('action_version')} {decision.get('parameters')}",
    }
    execution_id = f"AX-{decision_id}"
    execution = h.baseline.client.get(f"/executions/{execution_id}")
    calls += 1
    outcome_body = None
    if execution.status_code == 200:
        outcome_id = execution.json().get("outcome_id")
        if outcome_id:
            outcome_resp = h.baseline.client.get(f"/outcomes/{outcome_id}")
            calls += 1
            if outcome_resp.status_code == 200:
                outcome_body = outcome_resp.json()
    answers["what_actual_outcome"] = (outcome_body or {}).get("reconciliation_state")
    answers["what_changed_next"] = "no subsequent decision generated by this workload"
    elapsed = time.monotonic() - t0
    return {"variant": "baseline", "answers": answers, "calls": calls, "manual_sources": 1, "elapsed_s": elapsed, "complete": all(v not in (None, False, "") for k, v in answers.items() if k != "what_changed_next")}


def run(h: Harness) -> dict:
    part = synthetic.part_ids(5)
    synthetic.ensure_erp_part(h.erp_conn, part)
    synthetic.set_wms_inventory(h.wms_http.base_url, part, "WH-B", on_hand=60)
    synthetic.wait_both_converged(h.baseline_conn, h.ontology_hot_conn, part, "WH-B", 60, timeout_s=40.0)

    decision_ids = {}
    for name, client in h.clients.items():
        resp = client.propose("transfer_inventory", "user", "planner-1", {
            "source_warehouse": "WH-B", "destination_warehouse": "WH-A", "part": part.canonical_id, "quantity": 10,
        })
        decision_id = resp.json()["decision_id"]
        exec_resp = client.execute(decision_id)
        assert exec_resp.status_code == 202, exec_resp.text
        final = client.wait_terminal(decision_id, timeout_s=45.0)
        decision_ids[name] = decision_id
        assert final.get("status") == "OBSERVED_SUCCESS", final

    forensic = {
        "ontology": _forensic_ontology(h, decision_ids["ontology"]),
        "baseline": _forensic_baseline(h, decision_ids["baseline"]),
    }

    return {
        "workload": "W5_forensic_query",
        "decision_ids": decision_ids,
        "forensic": forensic,
        "part": part.canonical_id,
    }


def test_w5_forensic_query(harness: Harness):
    result = run(harness)
    for name, f in result["forensic"].items():
        assert f["complete"], (name, f)
